CREATE TABLE chat(
	ngày DATE PRIMARY KEY,
	lượt_truy_cập INT,
	lượt_chat INT,
	lượt_truy_cập_có_chat INT,
	tỷ_lệ_truy_cập_có_chat DECIMAL(5,2),
	phản_hồi_chat INT,
	chat_chưa_phản_hồi INT,
	thời_gian_phản_hồi INT,
	tỷ_lệ_chuyển_đổi_yêu_cầu_phản_hồi DECIMAL(5,2),
	tỷ_lệ_phản_hồi_chat DECIMAL(5,2),
	người_mua INT,
	đơn_hàng INT,
	sản_phẩm INT,
	doanh_số_đ INT,
	tỷ_lệ_chuyển_đổi_phản_hồi_đơn_được_đặt DECIMAL(5,2)
	)

CREATE TABLE details(
	Sản_phẩm NVARCHAR(150),
	Mã_sản_phẩm NVARCHAR(15),
	Tên_Phân_Loại NVARCHAR(50),
	Mã_phân_loại_hàng NVARCHAR(15),
	SKU_phân_loại NVARCHAR(15),
	SKU_sản_phẩm NVARCHAR(15),
	Lượt_truy_cập_sản_phẩm INT,
	Lượt_xem_trang_sản_phẩm INT,
	Số_lượng_khách_thoát_trang_sản_phẩm INT,
	Tỷ_lệ_thoát_Trang_sản_phẩm DECIMAL(5,2),
	Lượt_click_từ_Trang_tìm_kiếm INT,
	Lượt_thích INT,
	Lượt_truy_cập_sản_phẩm_Thêm_vào_giỏ_hàng INT,
	Sản_phẩm_Thêm_vào_giỏ_hàng INT,
	Tỷ_lệ_chuyển_đổi_theo_lượt_thêm_vào_giỏ_hàng DECIMAL(5,2),
	Người_mua_đã_đặt_hàng INT,
	Sản_phẩm_Đơn_đã_đặt INT,
	Doanh_số_Đơn_đã_đặt_VND INT,
	Tỷ_lệ_chuyển_đổi_Đơn_đã_đặt DECIMAL(5,2),
	Người_mua_có_đơn_đã_xác_nhận INT,
	Sản_phẩm_Đơn_đã_xác_nhận INT,
	Doanh_số_Đơn_đã_xác_nhận_VND INT,
	Tỷ_lệ_chuyển_đổi_Đơn_đã_xác_nhận DECIMAL(5,2),
	Tỷ_lệ_chuyển_đổi_Từ_Đơn_đã_đặt_thanh_Đơn_đã_xác_nhận DECIMAL(5,2))
	
CREATE TABLE product_overview(
	Ngày DATE,
	Lượt_truy_cập_sản_phẩm	INT,
	Lượt_xem_trang_sản_phẩm	INT,
	Sản_phẩm_được_truy_cập	INT,
	Số_lượng_khách_thoát_trang_sản_phẩm INT,
	Tỷ_lệ_thoát_Trang_sản_phẩm DECIMAL(5,2),
	Lượt_click_từ_Trang_tìm_kiếm	INT,
	Lượt_thích	INT,
	Lượt_truy_cập_sản_phẩm_Thêm_vào_giỏ_hàng	INT,
	Sản_phẩm_Thêm_vào_giỏ_hàng	INT,
	Tỷ_lệ_chuyển_đổi_theo_lượt_thêm_vào_giỏ_hàng	DECIMAL(5,2),
	Người_mua_đã_đặt_hàng	INT,
	Sản_phẩm_Đơn_đã_đặt	INT,
	Số_sản_phẩm_đã_bán	INT,
	Doanh_số_Đơn_đã_đặt_VND	INT,
	Tỷ_lệ_chuyển_đổi_Đơn_đã_đặt 	DECIMAL(5,2),
	Người_mua_có_đơn_đã_xác_nhận	INT,
	Sản_phẩm_Đơn_đã_xác_nhận	INT,
	Sản_phẩm_được_duyệt	INT,
	Doanh_số_Đơn_đã_xác_nhận_VND	INT,
	Tỷ_lệ_chuyển_đổi_Đơn_đã_xác_nhận	DECIMAL(5,2),
	Tỷ_lệ_chuyển_đổi_Từ_Đơn_đã_đặt_thành_Đơn_đã_xác_nhận DECIMAL(5,2))

CREATE TABLE sales(Ngày	DATE,
Lượt_truy_cập	INT,
Khách_đã_đặt_hàng_chưa_thanh_toán	INT,
Sản_phẩm_khách_chưa_thanh_toán	INT,
Tất_cả_các_đơn	INT,
Doanh_số_Đơn_đã_đặt_VND	INT,
Tỷ_lệ_chuyển_đổi_Từ_Lượt_truy_cập_thành_Đơn_được_đặt	DECIMAL(5,2),
Người_mua_có_đơn_đã_xác_nhận	INT,
Sản_phẩm_Đơn_đã_xác_nhận	INT,
Đơn_đã_xác_nhận	INT,
Doanh_số_Đơn_đã_xác_nhận_VND INT,	
Doanh_số_trên_mỗi_Người_mua_Đơn_đã_xác_nhận_VND	DECIMAL(10,2),
Tỷ_lệ_chuyển_đổi	DECIMAL(5,2),
Tỷ_lệ_chuyển_đổi_Từ_Đơn_đã_đặt_thành_Đơn_đã_xác_nhận DECIMAL(5,2))

CREATE TABLE traffic_overview(
Ngày DATE,
Lượt_xem INT,
Số_lượt_xem_trung_bình DECIMAL(5,2),
Thời_gian_xem_trung_bình INT,
Tỉ_lệ_thoát_trang DECIMAL(5,2),	
Lượt_truy_cập	INT,
Số_khách_truy_cập_mới	INT,
Số_khách_truy_cập_hiện_tại INT,	
Người_theo_dõi_mới INT)

CREATE TABLE discount_promotion(
Ngày_bắt_đầu DATE,
Ngày_kết_thúc	DATE,
Doanh_số_VND	INT,
Đơn_hàng	INT,
Số_lượng_sản_phẩm_đã_bán	INT,
Người_mua	INT,
Doanh_số_trên_mỗi_Người_mua_VND DECIMAL(10,2))

CREATE TABLE orders(
`Mã đơn hàng` NVARCHAR(20),
`Mã Kiện Hàng`	NVARCHAR(30),
`Ngày đặt hàng`DATETIME,
`Trạng Thái Đơn Hàng` NVARCHAR(20),	
`Lý do hủy`	NVARCHAR(200),
`Nhận xét từ Người mua`	NVARCHAR(200),
`Mã vận đơn`NVARCHAR(50),
`Đơn Vị Vận Chuyển` NVARCHAR(50),
`Phương thức giao hàng`	NVARCHAR(50),
`Loại đơn hàng`NVARCHAR(50),
`Ngày giao hàng dự kiến`	DATETIME,
`Ngày gửi hàng`	DATETIME,
`Thời gian giao hàng`	DATETIME,
`Trạng thái Trả hàng/Hoàn tiền`	NVARCHAR(50),
`SKU sản phẩm`	NVARCHAR(30),
`Tên sản phẩm`	NVARCHAR(200),
`Cân nặng sản phẩm` FLOAT,	
`Tổng cân nặng`	FLOAT,
`Cân nặng sản phẩm 1`	FLOAT,
`SKU phân loại hàng`	NVARCHAR(30),
`Tên phân loại hàng`	NVARCHAR(200),
`Giá gốc`	INT,
`Người bán trợ giá`	INT,
`Được Shopee trợ giá`	INT,
`Tổng số tiền được người bán trợ giá`	INT,
`Giá ưu đãi`	INT,
`Số lượng`	INT,
`Tổng giá bán (sản phẩm)`	INT,
`Tổng giá trị đơn hàng (VND)`	INT,
`Mã giảm giá của Shop`	INT,
`Hoàn Xu`	INT,
`Mã giảm giá của Shopee`	INT,
`Chỉ tiêu Combo Khuyến Mãi`	NVARCHAR(5),
`Giảm giá từ combo Shopee`	INT,
`Giảm giá từ Combo của Shop`	INT,
`Shopee Xu được hoàn`	INT,
`Số tiền được giảm khi thanh toán bằng thẻ Ghi nợ`	INT,
`Phí vận chuyển (dự kiến)`	INT,
`Phí vận chuyển mà người mua trả`	INT,
`Phí vận chuyển tài trợ bởi Shopee (dự kiến)`	INT,
`Phí trả hàng`	INT,
`Tổng số tiền người mua thanh toán`	INT,
`Thời gian hoàn thành đơn hàng`	DATETIME,
`Thời gian đơn hàng được thanh toán`	DATETIME,
`Phương thức thanh toán`	NVARCHAR(50),
`Phí cố định`	INT,
`Phí Dịch Vụ`	INT,
`Phí thanh toán`INT,
`Tiền ký quỹ`	INT,
`Người Mua`	NVARCHAR(50),
`Tên Người nhận`	NVARCHAR(50),
`Số điện thoại`	NVARCHAR(30),
`Tỉnh/Thành phố`	NVARCHAR(50),
`TP / Quận / Huyện`	NVARCHAR(50),
`Quận`	NVARCHAR(50),
`Địa chỉ nhận hàng`	NVARCHAR(200),
`Quốc gia`	NVARCHAR(20),
`Ghi chú` NVARCHAR(50));
